development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 400185452116-7ag31jfskohtlhi7nall1032gbh15652.apps.googleusercontent.com 
  google_client_secret: KqY9Jf7YZPLvtTCbojQWCXQT 
